### ISSUE TITLE
 connect_string for oraclepaas_java_service_instance #178 

### ISSUE THREAD

**Issue by tseoracle** [hashicorp/go-oracle-terraform#180]
Since I don't know how to reopen the issue, files new one just in case.
The following is the same comment added to #178.
"connect_string" still can't work.
It never be passed to PSM site as connectString parameter
2019-01-23T12:47:58.869-0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.2_x4: Body: {"availabilityDomain":"xxxx","backupDestination":"BOTH","cloudStorageContainer":"xxxxx","cloudStoragePassword":"xxxxx","cloudStorageUser":"xxxxx","components":,"WLS":{"adminPassword":"xxxxx","adminUserName":"weblogic","dbaName":"sys","dbaPassword":"xxxxx","domainMode":"PRODUCTION","shape":"VM.Standard2.2","adminPort":7001,"securedAdminPort":7002}},"edition":"EE",...
...
weblogic_server.0.connect_string: "" => "ssssdb-scan.ssss02.vcnnonprod.oraclevcn.com:1521/pdb1.ssss02.vcnnonprod.oraclevcn.com"
weblogic_server.0.database.#: "" => "1"
weblogic_server.0.database.0.hostname: "" => ""
weblogic_server.0.database.0.password: "" => ""
weblogic_server.0.database.0.username: "" => "sys"
weblogic_server.0.domain.#: "" => "1"
...
Error: Error applying plan:

1 error(s) occurred:

    oraclepaas_java_service_instance.ssssjcs1: 1 error(s) occurred:

    oraclepaas_java_service_instance.ssssjcs1: Error creating JavaServiceInstance: unable to create Java Service Instance "ssssjcs1": 400: {"details":{"message":"PSM-LCM-01001 Unable to submit request to create service [ssssjcs1] in domain [idcs-ba90ad8156664784b646d74f4b484597]. See the included validation errors for details.","issues":["[Both DB service name [dbServiceName] and connect string [connectString] cannot be null or empty]"]}}

**Comment by mbfrahry** [comment]
Hey @tseoracle, `connect_string` should now be useable in 1.4.3 of the oraclepaas provider.

**Comment by mbfrahry** [comment]
Feel free to close this if it works

**Comment by tseoracle** [comment]
v1.4.3 works.
Thank you.
